### ISSUE TITLE
dark version looks broken in VSCode

### ISSUE THREAD

**Issue by simonhermann** [philipbelesky/gray-matter#2]
Unfortunately the dark version leaves some UI elements like the file explorer light. 
Also tabs are barely readable. 
(Otherwise great theme for markdown!)

**Comment by philipbelesky** [comment]
Hey Simon, thanks for bringing this to my attention. I don't use VSCode often so this might be a regression or just bad testing on my part. I'll try and look into it and push up an update soon!

**Comment by philipbelesky** [comment]
@simonhermann the newly-published 1.3.0 update should address this, feel free to re-open this issue if it doesn't! 

Also there's probably a few tweaks to be made to the VSC theme; feel free to send along any `workbench.colorCustomizations` that you feel would help the theme.
