### ISSUE TITLE
VS Code Status Bar Coloring

### ISSUE THREAD

**Issue by bemayr** [philipbelesky/gray-matter#5]
Hi Philip!

First of all thanks for the great theme! 👏
While working with the light version in VS Code i just encountered an issue with the status bar coloring:
![image](https://user-images.githubusercontent.com/6529243/54742328-66fae200-4bc1-11e9-91e6-8746eca54059.png)

I just submitted a PR (#4) for this.

All the best, Bernhard

**Comment by philipbelesky** [comment]
Closed by #4, thanks again!
